import React, {useState} from 'react'
import Header from './Header.js';
import Homepage from './Homepage.js';
import Footer from './Footer';
import AddCardForm from './AddCardForm.js';
import CardView from './CardView.js';
import { BrowserRouter as Router,Routes, Route} from 'react-router-dom'

function App() {
  const onDelete = (card) =>{
    setCards(cards.filter((item)=>{
      return item!==card;
    }))
  }

  const addCard = (card) => {
    console.log("addingcard!");
    console.log(card);
    setCards(cards.concat(card));
  }

  const [cards, setCards] = useState([
    {
      ID:"435453",
      CARD_NAME: "test.vcf",
      FIRST_NAME: "Jhon",
      LAST_NAME: "Doe",
      ORGANIZATION: "Crieatzo",
      JOB_TITLE: "SME",
      ORG_DEPARTMENT: "IT",
      ADDRESS_1: "12345 First Avenue",
      ADDRESS_2: "street 2",
      CITY: "Kolkata",
      REGION: "West Bengal",
      POSTAL_CODE: "700139",
      COUNTRY: "India",
      EMAIL: "johndoe@email.com",
      WEBSITE: "https://fileinfo.com",
      PHONE_NO: "4353-5242",
      MOBILE_NO: "9123534652",
      TWITTER: "https://twitter.com/finkd",
      LINKEDIN: "https://www.linkedin.com/in/mark-zuckerberg-618bba58/",
      NOTES: "The man I met at the company networking event. He mentioned that he had some potential leads.",
    }
  ]);

  const downloadTxtFile = (card) => {
    const element = document.createElement("a");
    const vCardName = "\nN:"+card.LAST_NAME+";"+card.FIRST_NAME+";;;";
    const vCardFullName = "\nFN:"+card.FIRST_NAME+" "+card.LAST_NAME;
    const vCardTitle = "\nTITLE:"+card.JOB_TITLE;
    const vCardOrganiation = "\nORG:"+card.ORGANIZATION+";"+card.ORG_DEPARTMENT;
    const vcardAddress = "\nADR;type=HOME:;;"+card.POSTAL_CODE+card.ADDRESS_1+card.ADDRESS_2+";"+card.CITY+";"+card.REGION+";"+card.POSTAL_CODE+";"+card.COUNTRY;
    const vcardMail = "\nEMAIL;type=INTERNET,pref:"+card.EMAIL;
    const vcardPhone = "\nTEL;type=WORK,voice:"+card.PHONE_NO;
    const vcardMobile = "\nTEL;type=CELL,voice:"+card.MOBILE_NO;
    const vcardWebsite = "\nURL;type=WORK:"+card.WEBSITE;
    const vCardNote = "\nNOTE:"+card.NOTES+" - This vCard was generated by crieatazo";
    const vCard = "BEGIN:VCARD\nVERSION:3.0"+vCardFullName+vCardName+vCardTitle+vCardOrganiation+vcardAddress+vcardMail+
      vcardPhone+vcardMobile+vcardWebsite+vCardNote+"\nEND:VCARD";
    const file = new Blob([vCard],{type: 'text/plain; charset=utf-8'});
    element.href = URL.createObjectURL(file);
    element.download = card.CARD_NAME+".vcf";
    document.body.appendChild(element);
    element.click();
  }

  return (
  <div>
    <Router>
      <Header/>
      <Routes>
      <Route path='/' element={<Homepage cards ={cards} onDelete={onDelete} download={downloadTxtFile}/>}/>
      <Route path='/addcard' element={<AddCardForm addCard={addCard} />}/>
      <Route path='/view' element={<CardView download={downloadTxtFile}/>}/>
      </Routes>
      <Footer/>
    </Router>
  </div>
  );
}

export default App;
